config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, only: [:index, :new, :show, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end
  delete '/bookmarks/:id', to: 'bookmarks#destroy', as: :delete_bookmark
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates_uniqueness_of :movie, scope: :list
  validates :comment, presence: true, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true
  before_destroy :check_for_references
  

  def check_for_references
    if bookmarks.count > 0
      return false
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = List.find(@bookmark.list_id)
    @bookmark.destroy
    redirect_to list_path(@list)
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  
  def index
    @lists = List.all
  end
  
  def show
    @list = List.find(params[:id])
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<div class="form">
  <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.input :comment %>
    <%= f.association :movie %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/lists/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit %>
<% end %>

app/views/lists/_navbar.html.erb
<div class="navbar">
  <i class="fas fa-film"></i>
  <div>
    <%= link_to 'My lists', lists_path(:anchor => "container-lists") %>
    <%= link_to 'New list', new_list_path %>
  </div>
</div>

app/views/lists/index.html.erb
<div class="banner-main">
  <p>
    <span id="banner-typed-text"></span>
  </p>
</div>

<div id="my-lists">
  <div id="my-lists-top-bar">
    <h2>My Lists</h2>
    <%= link_to 'Create a movie list', new_list_path, :class => "btn btn-success"%>
  </div>
  <div id="container-lists">
    <% @lists.each do |list| %>
        <%= link_to list_path(list) do %>
          <div class="card-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path list.photo.key, width: 540, height: 300, crop: :fill %>')"><%=list.name%></div>
        <% end %>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="form">
  <%= render 'form' %>
</div>

app/views/lists/show.html.erb
<div class="banner-list" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<% cl_image_path @list.photo.key %>')">
  <h1><%= @list.name %></h1>
</div>
<div class="container-main">
  <div class="top-bar">
    <%= link_to 'Create a bookmark', new_list_bookmark_path(list_id = @list.id), :class => "btn btn-success" %>
    <%= link_to 'Delete ths list', @destroy, method: :delete, :class => "btn btn-danger" %>
  </div>
  <div id="container-bookmarks">
    <% @list.bookmarks.each do |bookmark| %>
      <% mi = bookmark.movie_id %>
      <div class="card-bookmark">
        <div class="container-image">
          <img src="<%= Movie.find(mi).poster_url %>" alt="<%= Movie.find(mi).title %> image">
        </div>
        <div class="title-rating">
          <p style= "font-weight: bold"><%= Movie.find(mi).title %> </p>
          <i class="fas fa-star"></i>
          <%= Movie.find(mi).rating %>
        </div>
        <p><%= Movie.find(mi).overview %></p>
        <div class="footer">
          <div>
            <i class="fas fa-quote-left">
            </i> <%= bookmark.comment %>
            <i class="fas fa-quote-right"></i>
          </div>
          <%= link_to 'Delete', delete_bookmark_path(bookmark), method: :delete, :style => "color: red" %>
        </div>
      </div>
    <% end %>
  </div>
</div>